### ISSUE TITLE
Problem downloading .mscz files (Japanese characters on name)

### ISSUE THREAD

**Issue by hp-ferreirabr** [Xmader/musescore-downloader#9]
Hello!
First, thank you very much for developing this script! Saved me a lot of times!!
Second, forgive my english :/ 

I am trying to download the scores of this set, but I can't get no one .mscz file!
https://musescore.com/user/3443166/sets/5100954

On browser dev tools (network tab), I found this

![image](https://user-images.githubusercontent.com/62249235/76764911-649b7b80-6774-11ea-8ca9-c4877d6c9a9f.png)

I don't know anything about script programming, but I suspect the error is because the name of the scores has Japanese characters. Any other file that I try to download, works normally.

![image](https://user-images.githubusercontent.com/62249235/76764952-75e48800-6774-11ea-842b-067a378137b5.png)

To test, I tried to download this other too, with Japanese characters on name.
https://musescore.com/zeref777x/yumetourou

![image](https://user-images.githubusercontent.com/62249235/76765811-c5778380-6775-11ea-82cd-2c25b70bbe55.png)

Didn't worked too.

**Comment by Xmader** [comment]
Thank you for telling me, 
It is now fixed.

This problem occurs because all characters in [`Content-Disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) HTTP header must be encoded in [RFC 5987](https://tools.ietf.org/html/rfc5987).

**Comment by hp-ferreirabr** [comment]
Well, thanks for fixing, but still not working with all...

I already had the file 01-23. I downloaded when it was free on MuseScore ("free", with the limit of 20 per day). Now I downloaded the file 24*¹ and the last archive*², but I'm already having problem to download these three archives:

https://musescore.com/user/3443166/scores/5977766
https://musescore.com/user/3443166/scores/5983384
https://musescore.com/user/3443166/scores/6001993

I'm having the same error as before.

Files that worked now:
*¹ https://musescore.com/user/3443166/scores/5910045
*² https://musescore.com/user/3443166/scores/2991836

Thanks for fixing, they are very much important for me. I'm following this project have years and now that it is finally done I was very sad because I couldn't download. Again, you saved me! But I really really want the last three that it's missing for me...

**Comment by hp-ferreirabr** [comment]
> Thank you for telling me,
> It is now fixed.
> 
> This problem occurs because all characters in [`Content-Disposition`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) HTTP header must be encoded in [RFC 5987](https://tools.ietf.org/html/rfc5987).

Well, thanks for fixing, but still not working with all...

I already had the file 01-23. I downloaded when it was free on MuseScore ("free", with the limit of 20 per day). Now I downloaded the file 24¹ and the last archive², but I'm already having problem to download these three archives:

https://musescore.com/user/3443166/scores/5977766
https://musescore.com/user/3443166/scores/5983384
https://musescore.com/user/3443166/scores/6001993

I'm having the same error as before.

Files that worked now:
*¹ https://musescore.com/user/3443166/scores/5910045
*² https://musescore.com/user/3443166/scores/2991836

Thanks for fixing, they are very much important for me. I've been following this project have years and now that it is finally done I was very sad because I couldn't download it. Once again, you saved me! But I really really want the last three that are missing for me...

**Comment by Xmader** [comment]
Thank you a lot for testing.
It is now fixed again.

[There is a 6 MB size limit on the AWS Lambda response payload](https://jun711.github.io/aws/handling-aws-api-gateway-and-lambda-413-error/#aws-lambda-payload-size-limit).
When the size of the `mscz` file is larger than 6 MB (6 000 000‬‬ bytes), the problem occurs.
